### ISSUE TITLE
Kanban Board Setup

### ISSUE THREAD

**Issue by paulsaenzsucre** [elafildecolor/space-travelers-hub#25]
### Kanban Board Setup

We are two micronauts in this team: @GutemaG and @elafildecolor.

This is the link to our Kanban board:

[https://github.com/elafildecolor/space-travelers-hub/projects/1](https://github.com/elafildecolor/space-travelers-hub/projects/1).

**Comment by Ghiftee** [comment]
## STATUS: APPROVED ♻️♻️
Hi @elafildecolor and @GutemaG , 

To highlight 👍🏽 
✔️ Cards with team three have been removed 
✔️ Points are equal
✔️ Issue contains details of your team

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀  
Congratulations! 🎉 


![](https://media.giphy.com/media/kyLYXonQYYfwYDIeZl/giphy.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**Comment by paulsaenzsucre** [comment]
Thanks for your review!!!!
Have a great day!!!!
